# -*- coding: utf-8 -*-
"""Maths_for_AI_II_Unit_2_slide 19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dF6D71CpSOTpzWh3BHSZfQSHZ8fc6tH6
"""

import math
print(math.sqrt(64))

#Installing and Importing Python Libraries
!pip install numpy
import numpy as np

#Istalling SCIPY
!pip install scipy
import scipy as sp

from scipy import stats

data = [2.3, 1.9, 2.8, 3.3, 2.1]
mean = stats.tmean(data)
print(mean)

#Installing matplotlib, importing it and Drawing a line in a diagram from position (1, 3) to position (8, 10)
!pip install matplotlib
import matplotlib.pyplot as plt

plt.plot([1, 80], [3, 100])
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot([0,1,2,3,4,5])

plt.show()

#Installing and importing Pandas library

!pip install pandas
import pandas as pd

#mounting the drive                  #skip this step
from google.colab import drive
drive.mount('/content/drive')

#Operations on Data frame using pandas

#loading the csv file
import pandas as pd

# Specify the path to the CSV file
file_path = '/content/drive/MyDrive/Salary12.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# Display the first few rows of the dataframe
print(data.head(5))

data.tail(5)

#To check the particular column type
data['Salary'].dtype

#To check all columns types
data.dtypes