# -*- coding: utf-8 -*-
"""Maths_for_AI_year_2_Unit_3_Mean_Median_Mode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S8TZtYYZgBMb8fhB1Pyfc0-TBz_iWx2W
"""

#Import libraries
import numpy as np
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import norm

from google.colab import drive #skip this step

# Mount Google Drive
drive.mount('/content/drive')

import pandas as pd

# Path to the CSV file in Google Drive
file_path = '/content/drive/MyDrive/SOCR-HeightWeight.csv'

# Read the CSV file
df = pd.read_csv(file_path)

# Display the first few rows of the dataframe
print(df.head())

#check info about dataset
df.info()

#cut only 'Height' column for our data
height = df.iloc[:, 1]
print(height)

#Let's find the mean
mean = height.mean()
print(mean)

#get median
median = height.median()
print(median)

#Get the mode
mode = height.mode()[9] #It will give the last one
print(mode)

