# -*- coding: utf-8 -*-
"""Maths_for_AI_II_Year2_Measures_of_Dispersion_Unit_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Jr80-Xclpevfbe2_tvnwQybjcqQQTKE
"""

#The Python code to calculate the variance, standard deviation, range, and interquartile range (IQR):
#Problem Statement : Imagine you're developing an AI model to predict house prices based on various features such as size, location, and number of rooms.

#Import necessary Libraries
import numpy as np
import scipy.stats as stats

# House prices dataset
house_prices = np.array([300000, 350000, 400000, 450000, 500000, 550000, 600000, 650000, 700000, 750000])

# Calculating mean
mean_price = np.mean(house_prices)

# Calculating variance
variance_price = np.var(house_prices)

# Calculating standard deviation
std_deviation_price = np.std(house_prices)

# Calculating range
range_price = np.ptp(house_prices)

# Calculating interquartile range (IQR)
q1 = np.percentile(house_prices, 25)
q3 = np.percentile(house_prices, 75)
iqr_price = q3 - q1

# Displaying the results
print("House Prices:", house_prices)
print("Mean Price:", mean_price)
print("Variance:", variance_price)
print("Standard Deviation:", std_deviation_price)
print("Range:", range_price)
print("Interquartile Range (IQR):", iqr_price)
