# -*- coding: utf-8 -*-
"""Unit_5_OCR_slide_51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnP5Qi9FVjKiw-MAWzyGD-x4DJgiXDgr
"""

import matplotlib
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# !pip install pytesseract
# !pip install tesseract

!sudo apt install tesseract-ocr
!pip install pytesseract

import cv2
import pytesseract

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Replace 'path/to/your/image.jpg' with the actual path to your image on Drive
image_path = '/content/drive/MyDrive/meme.jpg'

# Load the image using OpenCV (cv2)
import cv2
img = cv2.imread(image_path)

plt.figure(figsize=(5,5))
plt.title('PLAIN IMAGE')
plt.imshow(img); plt.xticks([]); plt.yticks([])
plt.savefig('img')

img.shape

text = pytesseract.image_to_string(img)
print(text.replace('\n', ''))

im = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plt.figure(figsize=(10,10))
plt.title('GRAYSCALE IMAGE')
plt.imshow(im, cmap='gray'); plt.xticks([]); plt.yticks([])
plt.savefig('img3.png',bbox_inches='tight')

_, im = cv2.threshold(img, 240, 255, 1)
plt.figure(figsize=(10,10))
plt.title('IMMAGINE BINARIA')
plt.imshow(im, cmap='gray'); plt.xticks([]); plt.yticks([])
plt.savefig('img4.png',bbox_inches='tight')
