# -*- coding: utf-8 -*-
"""Maths_for_AI_II_Year_2_Unit_5_Probaibilty_Distributions_slide_38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mN-eYjxG0PG9oF9L6GrCPzssS0yH0XRO
"""

#import necessary libraries and functions
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import binom, poisson, norm, uniform

# Discrete Distributions
# Binomial Distribution
# Binomial Distribution parameters
n_binom, p_binom = 10, 0.5
binomial_pmf = binom.pmf(np.arange(0, n_binom + 1), n_binom, p_binom)
plt.figure(figsize=(10, 6))
plt.bar(np.arange(0, n_binom + 1), binomial_pmf)
plt.title('Binomial Distribution')
plt.xlabel('Number of Successes')
plt.ylabel('Probability')
plt.show()

# Poisson Distribution
# Poisson Distribution parameters
mu_poisson = 3
poisson_pmf = poisson.pmf(np.arange(0, 10), mu_poisson)
plt.figure(figsize=(10, 6))
plt.bar(np.arange(0, 10), poisson_pmf)
plt.title('Poisson Distribution')
plt.xlabel('Number of Events')
plt.ylabel('Probability')
plt.show()

# Continuous Distributions
# Normal Distribution
# Normal Distribution parameters
mu_normal, sigma_normal = 0, 1
# Range for plotting continuous distributions
x_continuous = np.linspace(-5, 5, 100)
normal_pdf = norm.pdf(x_continuous, mu_normal, sigma_normal)
plt.figure(figsize=(10, 6))
plt.plot(x_continuous, normal_pdf)
plt.title('Normal Distribution')
plt.xlabel('x')
plt.ylabel('Density')
plt.show()

# Uniform Distribution
# Uniform Distribution parameters
a_uniform, b_uniform = 0, 1
x_uniform = np.linspace(a_uniform, b_uniform, 100)
uniform_pdf = uniform.pdf(x_uniform, loc=a_uniform, scale=b_uniform - a_uniform)
plt.figure(figsize=(10, 6))
plt.plot(x_uniform, uniform_pdf)
plt.title('Uniform Distribution')
plt.xlabel('x')
plt.ylabel('Density')
plt.show()
