# -*- coding: utf-8 -*-
"""Unit_1_Decision_tree_Machine_learning_lab_Slide_103_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkugMnyN7xXmfNMrHJxC-B8LBLAhIL0V
"""

from google.colab import drive

# Mount Google Drive (if not already mounted)
drive.mount('/content/drive')

import pandas as pd

# Specify the path to your CSV file within your Drive
file_path = '/content/drive/MyDrive/salaries.csv'  # Replace with your actual path

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Now you can work with your DataFrame (df)
print(df.head())  # Display the first few rows

inputs = df.drop('salary_more_then_100k',axis='columns')

target = df['salary_more_then_100k']

from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_job.fit_transform(inputs['job'])
inputs['degree_n'] = le_degree.fit_transform(inputs['degree'])

inputs

inputs_n = inputs.drop(['company','job','degree'],axis='columns')

inputs_n

target

from sklearn import tree
model = tree.DecisionTreeClassifier()

model.fit(inputs_n, target)

model.score(inputs_n,target)

#Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?
model.predict([[2,1,0]])

#Is salary of Google, Computer Engineer, Masters degree > 100 k ?
model.predict([[2,1,1]])